### ISSUE TITLE
Crashing regularly

### ISSUE THREAD

**Issue by tristansly** [jjw24/Wox.Plugin.QuickUninstaller#3]
Please open new issue in: https://github.com/jjw24/Wox.Plugin.QuickUninstaller/issues/new
1. upload log file: C:\Users\ech0-V\AppData\Roaming\FlowLauncher\Logs\1.10.0\2022-12-13.txt
2. copy below exception message

Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/13/2022 17:01:43
Exception:
Quick Uninstaller Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.QuickUninstaller
Author: Hogan Lee
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickUninstaller.Main.<>c__DisplayClass2_2.<Query>b__2(ProgramInfo p) in D:\a\Wox.Plugin.QuickUninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 200
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at QuickUninstaller.Main.Query(Query query) in D:\a\Wox.Plugin.QuickUninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 198
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-12-13.txt](https://github.com/jjw24/Wox.Plugin.QuickUninstaller/files/10223293/2022-12-13.txt)

Crashed on unin

**Comment by jjw24** [comment]
Hi there, my apologies for the delayed reply. This plugin is now superseded by [Uninstaller+](https://github.com/Jack251970/Flow.Launcher.Plugin.UninstallerPlus). From flow type `pm install Uninstaller+`
