### ISSUE TITLE
Error while inputing `uninstall` keyword.

### ISSUE THREAD

**Issue by CodeZhangBorui** [jjw24/Wox.Plugin.QuickUninstaller#4]
## Flow Launcher Information

```
Flow Launcher version: 1.10.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/14/2023 09:04:56
Exception:
Quick Uninstaller Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.QuickUninstaller
Author: Hogan Lee
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Collection was modified; enumeration operation may not execute.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at QuickUninstaller.Main.Query(Query query) in D:\a\Wox.Plugin.QuickU
[2023-01-14.txt](https://github.com/jjw24/Wox.Plugin.QuickUninstaller/files/10416276/2023-01-14.txt)
ninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 198
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by CodeZhangBorui** [comment]
[2023-01-14.txt](https://github.com/jjw24/Wox.Plugin.QuickUninstaller/files/10416278/2023-01-14.txt)

**Comment by deefrawley** [comment]
Hi @CodeZhangBorui , has this error been resolved with recent releases of Flow Launcher (I just installed and tried this plugin and it worked for me)?
