### ISSUE TITLE
Flow Launcher crash

### ISSUE THREAD

**Issue by Thibault-Savenkoff** [jjw24/Wox.Plugin.QuickUninstaller#6]
**Describe the bug**
Flow Launcher crash after exiting the module.

**To Reproduce**
1. Type `unin`
2. Press `space`
3. And just remove the `unin`
4. Flow Launcher Crash
5. See error

**Expected behavior**
Just quit the module.

**Screenshots**
Doesn't need Screenshots.

[**Logs**](https://github.com/jjw24/Wox.Plugin.QuickUninstaller/files/12621793/2023-09-15.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 23H2
**Smartphone (please complete the following information):**
 - Device: Samsung S20+ 5G (EU)
 - OS: Android 
 - Browser: Brave
 - Version: 13

**Additional context**
```
Flow Launcher version: 1.16.1
OS Version: 22631.2271
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 09/15/2023 18:22:51
Exception:
Quick Uninstaller Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.QuickUninstaller
Author: Hogan Lee
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Collection was modified; enumeration operation may not execute.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at QuickUninstaller.Main.Query(Query query) in D:\a\Wox.Plugin.QuickUninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 156
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by jjw24** [comment]
Hi there, my apologies for the delayed reply. This plugin is now superseded by [Uninstaller+](https://github.com/Jack251970/Flow.Launcher.Plugin.UninstallerPlus). From flow type `pm install Uninstaller+`
