### ISSUE TITLE
Still crashing regularly on use multiple machines

### ISSUE THREAD

**Issue by tristansly** [jjw24/Wox.Plugin.QuickUninstaller#7]
Please open new issue in: https://github.com/jjw24/Wox.Plugin.QuickUninstaller/issues
1. upload log file: C:\Users\ech0-V\AppData\Roaming\FlowLauncher\Logs\1.16.2\2023-11-18.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 19045.3754
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 11/18/2023 22:36:13
Exception:
Quick Uninstaller Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.QuickUninstaller
Author: Hogan Lee
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Collection was modified; enumeration operation may not execute.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at QuickUninstaller.Main.Query(Query query) in D:\a\Wox.Plugin.QuickUninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 156
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, my apologies for the delayed reply. This plugin is now superseded by [Uninstaller+](https://github.com/Jack251970/Flow.Launcher.Plugin.UninstallerPlus). From flow type `pm install Uninstaller+`
